# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXeuUeZXFhkUYe6Iu6NcJI-3-3OxuPy4
"""

grades = input().split()
total = 0

for grade in grades:
  total = total + int(grade)

average = total / len(grades)
print(average)