# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIlOipssYwVpvcLw6k9LDWNkT1WE25vK
"""

grades = input().split()

max_grade = grades[0]
min_grade = grades[0]

for grade in grades:
    if int(grade) > int(max_grade):
        max_grade = grade

    if int(grade) < int(min_grade):
        min_grade = grade

print(max_grade)
print(min_grade)