# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIlOipssYwVpvcLw6k9LDWNkT1WE25vK
"""

grades = input().split()
fai_number = 0

for grade in grades:
  if int(grade) < 60:
    fai_number += 1

print(fai_number)